### ISSUE TITLE
Question about porting this to other platforms

### ISSUE THREAD

**Issue by LouDnl** [laneboysrc/nrf24l01-rc#1]
Before I dive into this repository and surround my with all sorts of challenges I do not (yet) have the knowledge for.

Do you guys have any tips on how to port this to an stm32f103c8t6 or avr? Or maybe someone else has already done this?

**Comment by laneboysrc** [comment]
Hi,

there is no port to the STM32 platform that I am aware of.

Porting should however be quite easy. There is already an ARM Cortex M0 based implementation in the lpc812-nrf24l01-receiver/ folder. The code in there can be ported to STM32 with minimal effort.

Porting to AVR will be more of a challenge as it is quiet an old 8-bit platform, but do-able as well.

Note that this receivers are designed to work with the HobbyKing HK310 RC car transmitter, they do not work with any other transmitters. 
The HK310 is no longer for sale.

I do however also have a matching transmitter project for this receiver, which incidentally is based on STM32 (Bluepill boards): https://github.com/laneboysrc/rc-headless-transmitter
That one requires serious effort and knowledge to build though.

cheers, Werner

**Comment by LouDnl** [comment]
Thanks for your reply! I was indeed planning to port it to STM32 or another 32bit platform. I will have a dive into the code and see what I can whip up.

**Comment by LouDnl** [comment]
Just need to split the receiver code from the lpc812 code.
